### ISSUE TITLE
issue (turborepo): path and working-directory are fighting/confusing

### ISSUE THREAD

**Issue by dmitov** [crabnebula-dev/cloud-release#10]
I'm trying to setup a cloud release via Github CI, but I can't get the right parameters perhaps. 
From what I see 
* https://github.com/crabnebula-dev/cloud-release/blob/main/action.yml#L10 - path is where the cn cli is downloaded
* https://github.com/crabnebula-dev/cloud-release/blob/main/action.yml#L14 - working-directory is where you run the cli

## Expected Behavior
I expect that if I don't specify path (reason: as a developer, I should not care where the cli is), but I specify:
```
working-directory: "apps/desktop"
```
it should run the command in this working directory.

## Current Behavior
Due to https://github.com/crabnebula-dev/cloud-release/blob/main/action.yml#L92 and my setup:
```
- name: upload assets
  uses: crabnebula-dev/cloud-release@v0.2.0
  with:
    command: release upload ${{ env.CN_APPLICATION }} --framework tauri --channel beta
    api-key: ${{ secrets.CN_API_KEY }}
    working-directory: ./apps/desktop
```
the aforementioned line will be in the working-directory of ` ./apps/desktop` and try to run:
```
./"${{ inputs.path }}"/cn ${{ inputs.command }}
```
 where inputs.path will be `.`, thus resulting in:
``` 
././cn ${{ inputs.command }}
``` 
and erroring out, due to the cn executable not being found, as it's installed in the `.` (home) folder of the OS running it.

Furthermore, if I specify the `path` to be the same as `working-directory`, it again errors out, as it tries to find the executable in:
```
./apps/desktop/./apps/desktop/cn
```
## Possible Solution
I'm not sure if we should be able to change `path`, instead remove this property and aways install it in the same place. The only thing a developer could be able to change is the `working-directory`, where they can specify the app they're trying to release.

This will result in less clutter in the setup.

## Possible Implementation

Remove the `path` input and leave only `working-directory`. I can submit a PR if this is okay with you guys.

In the meanwhile I'm using a local action, like this:
```
name: "cn-cloud-release"
description: "CrabNebula Cloud Release GitHub Action"
inputs:
  ...
  working-directory:
    description: 'Current working directory to use when running the CLI (your app path)'
    required: false
    default: "."
    
...
runs:
  using: "composite"
  steps:
    ...
    - name: Download CLI (Linux)
      shell: bash
      if: steps.restore-cache.outputs.cache-hit != 'true' && runner.os == 'Linux'
      working-directory: ${{ inputs.working-directory }}
      run: ..

    - name: Download CLI (macOS)
      shell: bash
      if: steps.restore-cache.outputs.cache-hit != 'true' && runner.os == 'macOS'
      working-directory: ${{ inputs.working-directory }}
      run: ..

    - name: Download CLI (Windows)
      shell: bash
      if: steps.restore-cache.outputs.cache-hit != 'true' && runner.os == 'Windows'
      working-directory: ${{ inputs.working-directory }}
      run: ..
  
    - name: "Run Command"
      id: run-command
      shell: bash
      env:
        CN_API_KEY: ${{ inputs.api-key }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        : cn ${{ inputs.command }}
        exec 5>&1
        OUTPUT=$(./cn ${{ inputs.command }} | tee >(cat - >&5))
        echo "stdout<<nEOFn" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "nEOFn" >> $GITHUB_OUTPUT

**Comment by lucasfernog-crabnebula** [comment]
I wanted to remove the `path` input but I didn't want to introduce any breaking change.

I'll work to fix this issue.
